### PR TITLE
Fix serve and funnel commands

### LINKED ISSUE #9: The mod doesn't work with the current version of tailscale
Tailscale 1.52.0 changed the `tailscale serve` CLI, which means this docker mode doesn't work anymore.

Current `main` call: 

```
tailscale serve "${TAILSCALE_SERVE_MODE}":443 / http://localhost:"${TAILSCALE_SERVE_PORT}"
```

I believe this should be

```
tailscale serve --bg --https=443 http://localhost:"${TAILSCALE_SERVE_PORT}"
```

instead (but I'm not fully sure if this is a full equivalent).

### PR DESCRIPTION
**Pull request by timtailscale**
Updates the serve and funnel commands to the new format used in Tailscale version 1.52.0 and above. Fixes #9.

### CODE REVIEW

File: root/etc/s6-overlay/s6-rc.d/svc-tailscale-up/run [hunk 1]
```diff
@@ -26,18 +26,13 @@ tailscale up $FLAGS
...
-    else
-        tailscale serve "${TAILSCALE_SERVE_MODE}":443 http://localhost:"${TAILSCALE_SERVE_PORT}"
-    fi
+    tailscale serve --bg --"${TAILSCALE_SERVE_MODE}"=443 http://localhost:"${TAILSCALE_SERVE_PORT}"
 fi
 
 # configure funnel
 if [ -v TAILSCALE_FUNNEL ]; then
-    tailscale funnel 443 on
+    tailscale funnel --bg --"${TAILSCALE_SERVE_MODE}"=443 http://localhost:"${TAILSCALE_SERVE_PORT}"
```
Comment (tylersmalley) [inline root/etc/s6-overlay/s6-rc.d/svc-tailscale-up/run:34]: While this will work - it would be better to call either `server` or `funnel` depending on if `TAILSCALE_FUNNEL` is provided.

**Review by tylersmalley — APPROVED** [review]
